from odoo import api, SUPERUSER_ID

identificadores = [
    'l10n_ar.1_ri_tax_percepcion_iva_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iva_sufrida',
    'l10n_ar.1_ri_tax_percepcion_ganancias_aplicada',
    'l10n_ar.1_ri_tax_percepcion_ganancias_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_caba_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_caba_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_az_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_az_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_ba_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_ba_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_ca_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_ca_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_co_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_co_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_ct_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_ct_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_er_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_er_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_fo_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_fo_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_ha_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_ha_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_ju_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_ju_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_lp_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_lp_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_lr_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_lr_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_mi_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_mi_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_ne_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_ne_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_nn_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_nn_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_rn_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_rn_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_rr_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_rr_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_sa_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_sa_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_se_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_se_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_sf_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_sf_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_sl_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_sl_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_tf_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_tf_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_tn_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_tn_sufrida',
    'l10n_ar.1_ri_tax_percepcion_iibb_za_aplicada',
    'l10n_ar.1_ri_tax_percepcion_iibb_za_sufrida',
    'l10n_ar.par_iibb_pagar',
    'product.product_category_1',
    'product.cat_expense',
    'hr.employee_admin',
    'hr.res_partner_admin_private_address',
]

def generic_pre_init_hook(cr):
    env = api.Environment(cr, SUPERUSER_ID, {})
    for identificador in identificadores:
        if env.ref(identificador, raise_if_not_found=False):
            env.ref(identificador).unlink()
